[project]
name = "skillner"
version = "2.0.dev"
requires-python = ">=3.9"


[project.optional-dependencies]
doc = [
    "sphinx",
    "numpydoc",
    "sphinx_copybutton",
    "furo"
]

dev = [
    "pytest",
    "black",
    "skillner[doc]",
]
